pipeline{
  agent any

  tools{
    maven 'maven 3.9.8'
  }
  
  stages{
    stage("build"){
      echo 'Compiling worker app'
      dir('worker'){
        sh 'mvn compile'
      }
    }
    stage("test"){
      steps{
        echo 'Running Unit Tests on worker app'
        sh 'mvn clean test'
      }
    }
    stage('package'){
      steps{
        echo 'Packaging worker app'
        sh 'mvn package'
      }
    }
  }

  post{
    always{
      echo 'Building multibranch pipeline for worker is completed..'
    }
  }
}
